name: rust-rustfmt-check
description: Format Rust code using rustfmt
author: mbrobbel
branding:
  icon: feather
  color: yellow

inputs:
  token:
    description: GitHub token
    required: true
  args:
    description: Arguments for cargo. Not for rustfmt options.
    required: false
  mode:
    type: choice
    description: Output mode
    default: commit
    options:
      - commit
      - review
    required: false

runs:
  using: node16
  main: dist/index.js
