name: rust-rustfmt-check
description: Format Rust code using rustfmt
author: mbrobbel
branding:
  icon: feather
  color: yellow

inputs:
  token:
    description: GitHub token
    required: true
  args:
    description: Arguments for cargo.
    required: false
  rustfmt-args:
    description: Arguments for rustfmt.
    required: false
  mode:
    description: Output mode (commit, review or pull)
    default: commit
    required: false
  commit-message:
    description: Commit message for formatting commits.
    required: false
    default: Format Rust code using rustfmt
  working-directory:
    description: Directory to run cargo fmt in.
    required: false
    default: .
  override-nightly:
    description: Whether to add +nightly to cargo invocation.
    default: "true"
    required: false

runs:
  using: node20
  main: dist/index.js
