name: Action

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        override: true
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
